# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import proto_env_message_pb2 as proto__env__message__pb2


class TurnBasedServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetObservation = channel.unary_unary(
        '/protos.TurnBasedServer/GetObservation',
        request_serializer=proto__env__message__pb2.RequestInfo.SerializeToString,
        response_deserializer=proto__env__message__pb2.NDArray.FromString,
        )


class TurnBasedServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetObservation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TurnBasedServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetObservation': grpc.unary_unary_rpc_method_handler(
          servicer.GetObservation,
          request_deserializer=proto__env__message__pb2.RequestInfo.FromString,
          response_serializer=proto__env__message__pb2.NDArray.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.TurnBasedServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
